import CoverImage from "@/assets/blog/cover.png";
import Avatar from "@/assets/blog/Avatar.png";

export const BlogData = [
	{
		id: 1,
		featured: true,
		title: "Title",
		avatar: Avatar,
		author: "Beth Carmy",
		date: "10th May 2025",
		coverImage: CoverImage,
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin mollis nunc sit amet rhoncus tincidunt. Etiam condimentum ligula enim, in tincidunt lectus interdum non. Integer vitae eleifend dolor. Nullam ut convallis arcu, non pharetra urna. Nulla commodo placerat est, ac congue metus pulvinar a. Nam in massa non libero efficitur cursus sit amet sed odio. In hac habitasse platea dictumst. Aliquam a magna quis dui cursus maximus vel et magna. Nullam eget massa massa. Aliquam sed sem leo. Quisque dui leo, pretium at turpis vitae, laoreet finibus sem. Nulla at lacus quis velit eleifend venenatis. Donec sagittis elementum dui, eu interdum lorem sagittis eget.",
	},
	{
		id: 2,
		featured: false,
		title: "Title 2",
		avatar: Avatar,
		author: "Beth Carmy",
		date: "11th May 2025",
		coverImage: CoverImage,
		body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Tra la la la nunc sit amet rhoncus tincidunt. Etiam condimentum ligula enim, in tincidunt lectus interdum non. Integer vitae eleifend dolor. Nullam ut convallis arcu, non pharetra urna. Nulla commodo placerat est, ac congue metus pulvinar a. Nam in massa non libero efficitur cursus sit amet sed odio. In hac habitasse platea dictumst. Aliquam a magna quis dui cursus maximus vel et magna. Nullam eget massa massa. Aliquam sed sem leo. Quisque dui leo, pretium at turpis vitae, laoreet finibus sem. Nulla at lacus quis velit eleifend venenatis. Donec sagittis elementum dui, eu interdum lorem sagittis eget.",
	},
	{
		id: 3,
		featured: false,
		title: "Title3",
		avatar: Avatar,
		author: "Beth Carmy",
		date: "10th May 2025",
		coverImage: CoverImage,
		body: "Navigating the complexities of remote team management demands a strategic and nuanced approach. The shift towards distributed workforces presents both opportunities and distinct challenges for leadership. This professional discourse outlines ten critical considerations for cultivating a high-performing and cohesive remote team.Paramount to success is the establishment of a robust communication architecture. Strategic and transparent communication protocols are not merely beneficial; they are foundational. Leaders must implement a multi-faceted communication strategy encompassing synchronous channels for dynamic collaboration and asynchronous platforms for thoughtful, time-zone-agnostic information exchange. Clear guidelines on channel usage and expected response times are essential for operational efficiency.Building a culture of trust and autonomy is equally vital. Micromanagement, often a symptom of insecurity, can stifle innovation and erode morale. Effective remote leadership necessitates clearly defined objectives, empowering team members with the agency to determine their optimal work processes. Performance evaluation should focus on outcomes rather than surveillance of activity.The spontaneous interactions inherent in co-located environments are often lost in remote settings. Proactive measures to foster virtual social cohesion are therefore necessary. This can involve dedicated virtual spaces for non-work-related dialogue, the incorporation of virtual team-building exercises, and the encouragement of informal digital interactions to cultivate camaraderie.Recognizing the diverse operational realities of remote team members necessitates a commitment to flexible and adaptable work policies. Individual circumstances, ranging from varying time zones to differing home environments, require a leadership approach that prioritizes outcomes while accommodating individual needs and work styles.In the absence of constant physical presence, structured and consistent feedback mechanisms are crucial for individual growth and team alignment. Regular, scheduled one-on-one meetings focused on performance, challenges, and professional development are essential. Furthermore, fostering a culture of reciprocal feedback encourages continuous improvement.In conclusion, managing a high-performing remote team requires a deliberate and thoughtful approach that prioritizes clear communication, trust-based autonomy, social connectivity, flexibility, consistent feedback, transparency, recognition, adequate resources, and exemplary leadership. By embracing these professional considerations, organizations can cultivate thriving remote teams capable of achieving exceptional results.",
	},
	{
		id: 4,
		featured: false,
		title: "Title 4",
		avatar: Avatar,
		author: "Beth Carmy",
		date: "13th May 2025",
		coverImage: CoverImage,
		body: "Lorem ipsum dolor sit amet, 444 consectetur adipiscing elit. Proin mollis nunc sit amet rhoncus tincidunt. Etiam condimentum ligula enim, in tincidunt lectus interdum non. Integer vitae eleifend dolor. Nullam ut convallis arcu, non pharetra urna. Nulla commodo placerat est, ac congue metus pulvinar a. Nam in massa non libero efficitur cursus sit amet sed odio. In hac habitasse platea dictumst. Aliquam a magna quis dui cursus maximus vel et magna. Nullam eget massa massa. Aliquam sed sem leo. Quisque dui leo, pretium at turpis vitae, laoreet finibus sem. Nulla at lacus quis velit eleifend venenatis. Donec sagittis elementum dui, eu interdum lorem sagittis eget.",
	},
	{
		id: 5,
		featured: false,
		title: "Title 5",
		avatar: Avatar,
		author: "Beth Carmy",
		date: "13th May 2025",
		coverImage: CoverImage,
		body: "Lorem ipsum dolor sit amet, 444 consectetur adipiscing elit. Proin mollis nunc sit amet rhoncus tincidunt. Etiam condimentum ligula enim, in tincidunt lectus interdum non. Integer vitae eleifend dolor. Nullam ut convallis arcu, non pharetra urna. Nulla commodo placerat est, ac congue metus pulvinar a. Nam in massa non libero efficitur cursus sit amet sed odio. In hac habitasse platea dictumst. Aliquam a magna quis dui cursus maximus vel et magna. Nullam eget massa massa. Aliquam sed sem leo. Quisque dui leo, pretium at turpis vitae, laoreet finibus sem. Nulla at lacus quis velit eleifend venenatis. Donec sagittis elementum dui, eu interdum lorem sagittis eget.",
	},
	{
		id: 6,
		featured: false,
		title: "Title 6",
		avatar: Avatar,
		author: "Beth Carmy",
		date: "13th May 2025",
		coverImage: CoverImage,
		body: "Lorem ipsum dolor sit amet, 444 consectetur adipiscing elit. Proin mollis nunc sit amet rhoncus tincidunt. Etiam condimentum ligula enim, in tincidunt lectus interdum non. Integer vitae eleifend dolor. Nullam ut convallis arcu, non pharetra urna. Nulla commodo placerat est, ac congue metus pulvinar a. Nam in massa non libero efficitur cursus sit amet sed odio. In hac habitasse platea dictumst. Aliquam a magna quis dui cursus maximus vel et magna. Nullam eget massa massa. Aliquam sed sem leo. Quisque dui leo, pretium at turpis vitae, laoreet finibus sem. Nulla at lacus quis velit eleifend venenatis. Donec sagittis elementum dui, eu interdum lorem sagittis eget.",
	},
	{
		id: 7,
		featured: false,
		title: "Title 7",
		avatar: Avatar,
		author: "Beth Carmy",
		date: "13th May 2025",
		coverImage: CoverImage,
		body: "Lorem ipsum dolor sit amet, 444 consectetur adipiscing elit. Proin mollis nunc sit amet rhoncus tincidunt. Etiam condimentum ligula enim, in tincidunt lectus interdum non. Integer vitae eleifend dolor. Nullam ut convallis arcu, non pharetra urna. Nulla commodo placerat est, ac congue metus pulvinar a. Nam in massa non libero efficitur cursus sit amet sed odio. In hac habitasse platea dictumst. Aliquam a magna quis dui cursus maximus vel et magna. Nullam eget massa massa. Aliquam sed sem leo. Quisque dui leo, pretium at turpis vitae, laoreet finibus sem. Nulla at lacus quis velit eleifend venenatis. Donec sagittis elementum dui, eu interdum lorem sagittis eget.",
	},
];
