import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

import NavBar from "@/sections/NavBar";
import Footer from "@/sections/Footer";

const outfit = Outfit({
	variable: "--font-outfit",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "NextJS App Template",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${outfit.className} antialiased`}>
				<NavBar />

				{children}

				<Footer />
			</body>
		</html>
	);
}
